service: anime-art-gen
useDotenv: true

plugins:
  - serverless-domain-manager

package:
  patterns:
    - '!src/**'
    - '!node_modules/**'
    - '!migrations/**'
    - '!drizzle.config.ts'
  
custom:
  customDomain:
    domainName: api.anime-art-gen.com
    basePath: ''
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: true


provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  timeout: 30
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    DATABASE_AUTH_TOKEN: ${env:DATABASE_AUTH_TOKEN}
    JWT_SECRET: ${env:JWT_SECRET}
    RESEND_FROM_EMAIL: ${env:RESEND_FROM_EMAIL}
    RESEND_API_KEY: ${env:RESEND_API_KEY}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
    REPLICATE_API_TOKEN: ${env:REPLICATE_API_TOKEN}
    REPLICATE_CALLBACK_URL: ${env:REPLICATE_CALLBACK_URL}
    REPLICATE_SIGNING_KEY: ${env:REPLICATE_SIGNING_KEY}
    IMAGE_GENERATION_REQUEST_TOPIC: ${env:IMAGE_GENERATION_REQUEST_TOPIC}
    IMAGE_GENERATION_START_TOPIC: ${env:IMAGE_GENERATION_START_TOPIC}
    IMAGE_GENERATION_SUCCESS_TOPIC: ${env:IMAGE_GENERATION_SUCCESS_TOPIC}

  iam:
      role:
        name: lambda-anime-art-gen-${opt:stage}-role
        statements:
          - Effect: "Allow"
            Action:
              - "s3:*"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "sns:*"
            Resource: "*"

          - Effect: "Allow"
            Action:
              - "sqs:*"
            Resource: "*"

          - Effect: "Allow"
            Action:
              - "ses:*"
            Resource: "*"

          - Effect: "Allow"
            Action:
              - "dynamodb:*"
            Resource: "*"


functions:
  api:
    handler: dist/api.handler
    events:
      - http:
          path: "{proxy+}"
          method: ANY

  start-generation:
    handler: dist/startGeneration.handler
    events:
       - sqs: arn:aws:sqs:us-east-1:556737114908:image_generation_requests
    
  